version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jeffbook-php:8.4
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - jeffbook-net
    depends_on:
      - mysql
      - redis
  web:
    image: nginx:stable-alpine
    container_name: jeffbook-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - jeffbook-net
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: jeffbook-mysql
    ports:
      - "13036:13036"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: jeffbook
      MYSQL_USER: jeffbook
      MYSQL_PASSWORD: secret
    volumes:
      - jeffbook-mysql:/var/lib/mysql
    networks:
      - jeffbook-net

  redis:
    image: redis:alpine
    container_name: jeffbook-redis
    ports:
      - "6380:6380"
    volumes:
      - jeffbook-redis:/data
    networks:
      - jeffbook-net

  mailhog:
    image: mailhog/mailhog
    container_name: jeffbook-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - jeffbook-net

networks:
  jeffbook-net:
    driver: bridge

volumes:
  jeffbook-mysql:
  jeffbook-redis:
